/*
 * ╔══════════════════════════════════════════════╗
 * ║  This file is automatically generated by     ║
 * ║  Typest - typed asset paths for TypeScript.  ║
 * ║                                              ║
 * ║  Any edits you make here will be silently    ║
 * ║  overwritten the next time you run the dev   ║
 * ║  server or build your project.               ║
 * ║                                              ║
 * ║  To change which assets are included, edit   ║
 * ║  your vite config (typedAssets sources).     ║
 * ╚══════════════════════════════════════════════╝
 */

declare module '@typest/vite' {
  /** ========== Image Assets ========== */
  const imageAssets: {
    readonly "icons.svg": "/icons.svg";
    readonly "vite.svg": "/vite.svg";
    readonly "react.svg": "/assets/react.svg";
    readonly "favicon.svg": "/images/favicon.svg";
  };
  type ImageKey = keyof typeof imageAssets;
  export function imagePath(key: ImageKey): string;

  /** ========== Video Assets ========== */
  const videoAssets: {
    readonly "vid.mp4": "/vid.mp4";
  };
  type VideoKey = keyof typeof videoAssets;
  export function videoPath(key: VideoKey): string;

}
