import path from "node:path";
import fs from "node:fs/promises";
import { scanAssets } from "@typest/core";
import type { AssetSource, GeneratorOptions, AssetEntry } from "@typest/core";

// ---------------------------------------------------------------------------
// Public options
// ---------------------------------------------------------------------------
export interface NextTypedAssetsOptions {
  sources: AssetSource[];
  generator?: GeneratorOptions;
}

// ---------------------------------------------------------------------------
// Runtime helpers (fallback – just return the path, public assets are at root)
// ---------------------------------------------------------------------------
export function imagePath(key: string): string {
  return "/" + key;
}
export function videoPath(key: string): string {
  return "/" + key;
}
export function audioPath(key: string): string {
  return "/" + key;
}
export function fontPath(key: string): string {
  return "/" + key;
}
export function rawPath(key: string): string {
  return "/" + key;
}
export function assetPath(key: string): string {
  return "/" + key;
}

// ---------------------------------------------------------------------------
// Type generation
// ---------------------------------------------------------------------------
const DECLARATION_FILE = ".assets/types.d.ts"; // ← hidden folder, no src/

async function generateDeclarationFile(
  sources: AssetSource[],
  generatorOptions?: GeneratorOptions,
) {
  const entries = await scanAssets(sources, { keyStrategy: "filename" });
  const dts = buildDeclaration(entries, generatorOptions);
  const fullPath = path.resolve(DECLARATION_FILE);
  await fs.mkdir(path.dirname(fullPath), { recursive: true });
  await fs.writeFile(fullPath, dts, "utf-8");
}

function buildDeclaration(
  entries: AssetEntry[],
  options?: GeneratorOptions,
): string {
  const perType = options?.perType ?? true;
  let code = `// Auto-generated by typed-assets. DO NOT EDIT.\n\n`;
  code += `declare module '@typest/next' {\n`;

  if (perType) {
    const groups = groupByType(entries);
    const typeFuncMap: Record<string, string> = {
      image: "imagePath",
      video: "videoPath",
      audio: "audioPath",
      font: "fontPath",
      raw: "rawPath",
      generic: "assetPath",
    };
    for (const [type, assets] of groups) {
      if (!assets.length) continue;
      const constName = `${type}Assets`;
      const typeName = `${capitalize(type)}Key`;
      const funcName = typeFuncMap[type] || "assetPath";
      code += `  export const ${constName}: {\n`;
      assets.forEach((a) => (code += `    readonly "${a.key}": "${a.url}";\n`));
      code += `  };\n`;
      code += `  export type ${typeName} = keyof typeof ${constName};\n`;
      code += `  export function ${funcName}(key: ${typeName}): string;\n\n`;
    }
  } else {
    code += `  export const assets: {\n`;
    entries.forEach((a) => (code += `    readonly "${a.key}": "${a.url}";\n`));
    code += `  };\n`;
    code += `  export type AssetKey = keyof typeof assets;\n`;
    code += `  export function assetPath(key: AssetKey): string;\n`;
  }
  code += `}\n`;
  return code;
}

function groupByType(entries: AssetEntry[]): Map<string, AssetEntry[]> {
  const groups = new Map<string, AssetEntry[]>();
  entries.forEach((e) => {
    const list = groups.get(e.type) || [];
    list.push(e);
    groups.set(e.type, list);
  });
  return groups;
}

function capitalize(s: string) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

// ---------------------------------------------------------------------------
// Next.js config wrapper
// ---------------------------------------------------------------------------
export function withTypedAssets(options: NextTypedAssetsOptions) {
  const { sources, generator } = options;

  return async (nextConfig: any): Promise<any> => {
    // Generate the type declarations before Next.js starts
    await generateDeclarationFile(sources, generator);
    return { ...nextConfig };
  };
}
