/*
 * ╔══════════════════════════════════════════════╗
 * ║  This file is automatically generated by     ║
 * ║  Typest - typed asset paths for TypeScript.  ║
 * ║                                              ║
 * ║  Any edits you make here will be silently    ║
 * ║  overwritten the next time you run the dev   ║
 * ║  server or build your project.               ║
 * ║                                              ║
 * ║  To change which assets are included, edit   ║
 * ║  your vite config (typedAssets sources).     ║
 * ╚══════════════════════════════════════════════╝
 */

declare module "@typest/nextjs" {
  /* ╔════════════════╗
     ║  Image Assets  ║
     ╚════════════════╝ */
  const imageAssets: {
    readonly "file.svg": "/file.svg";
    readonly "globe.svg": "/globe.svg";
    readonly "next.svg": "/next.svg";
    readonly "vercel.svg": "/vercel.svg";
    readonly "window.svg": "/window.svg";
  };
  type ImageKey = keyof typeof imageAssets;
  export function imagePath(key: ImageKey): string;
}
