export function createHeader({
  framework,
  version,
}: {
  framework: string;
  version: string;
}) {
  const docs =
    framework === "vite"
      ? "https://thetypest.vercel.app/plugin/vite.html"
      : framework === "next"
        ? "https://thetypest.vercel.app/plugin/next.html"
        : "https://thetypest.vercel.app";

  return `/**
 * Generated by Typest CLI v${version}
 * Framework: ${framework}
 *
 * This file enables typed asset imports.
 * Learn more: ${docs}
 *
 * You can safely modify it as needed.
 */
`;
}

export function ensureHeader(content: string, header: string) {
  if (content.includes("Generated by Typest CLI")) return content;
  return `${header}\n${content}`;
}
