import path from "node:path";
import fs from "node:fs/promises";
import type { Plugin, ResolvedConfig } from "vite";
import { scanAssets } from "@typest/core";
import type { AssetSource, GeneratorOptions, AssetEntry } from "@typest/core";

export interface ViteTypedAssetsOptions {
  sources: AssetSource[];
  generator?: GeneratorOptions;
}

/** The sub‑path that users import from. */
const ASSET_IMPORT_PATH = "@typest/vite";
const RESOLVED_ASSET_IMPORT_PATH = "\0" + ASSET_IMPORT_PATH;
const DECLARATION_FILE = "src/assets.d.ts";

function generateDeclarationModule(
  entries: AssetEntry[],
  options?: GeneratorOptions,
): string {
  const perType = options?.perType ?? true;
  let dts = `// Auto-generated by typed-assets. DO NOT EDIT.\n\n`;
  dts += `declare module '${ASSET_IMPORT_PATH}' {\n`; // ← declares the import path

  if (perType) {
    const groups = groupByType(entries);
    const typeFuncMap: Record<string, string> = {
      image: "imagePath",
      video: "videoPath",
      audio: "audioPath",
      font: "fontPath",
      raw: "rawPath",
      generic: "assetPath",
    };
    for (const [type, assets] of groups) {
      if (!assets.length) continue;
      const constName = `${type}Assets`;
      const typeName = `${capitalize(type)}Key`;
      const funcName = typeFuncMap[type] || "assetPath";

      dts += `  export const ${constName}: {\n`;
      assets.forEach((a) => (dts += `    readonly "${a.key}": "${a.url}";\n`));
      dts += `  };\n`;
      dts += `  export type ${typeName} = keyof typeof ${constName};\n`;
      dts += `  export function ${funcName}(key: ${typeName}): string;\n\n`;
    }
  } else {
    dts += `  export const assets: {\n`;
    entries.forEach((a) => (dts += `    readonly "${a.key}": "${a.url}";\n`));
    dts += `  };\n`;
    dts += `  export type AssetKey = keyof typeof assets;\n`;
    dts += `  export function assetPath(key: AssetKey): string;\n`;
  }
  dts += `}\n`;
  return dts;
}

function generateVirtualModule(
  entries: AssetEntry[],
  options?: GeneratorOptions,
): string {
  // Pure JS code (no TypeScript syntax)
  const perType = options?.perType ?? true;
  let code = `// Generated by typed-assets\n`;
  if (perType) {
    const groups = groupByType(entries);
    const funcMap: Record<string, string> = {
      image: "imagePath",
      video: "videoPath",
      audio: "audioPath",
      font: "fontPath",
      raw: "rawPath",
      generic: "assetPath",
    };
    for (const [type, assets] of groups) {
      if (!assets.length) continue;
      const constName = `${type}Assets`;
      const funcName = funcMap[type] || "assetPath";
      code += `export const ${constName} = {\n`;
      assets.forEach((a) => (code += `  "${a.key}": "${a.url}",\n`));
      code += `};\n`;
      code += `export function ${funcName}(key) { return ${constName}[key]; }\n\n`;
    }
  } else {
    code += `export const assets = {\n`;
    entries.forEach((a) => (code += `  "${a.key}": "${a.url}",\n`));
    code += `};\n`;
    code += `export function assetPath(key) { return assets[key]; }\n`;
  }
  return code;
}

function groupByType(entries: AssetEntry[]): Map<string, AssetEntry[]> {
  const groups = new Map<string, AssetEntry[]>();
  entries.forEach((e) => {
    const list = groups.get(e.type) || [];
    list.push(e);
    groups.set(e.type, list);
  });
  return groups;
}

function capitalize(s: string) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

export function typedAssets(options: ViteTypedAssetsOptions): Plugin {
  let config: ResolvedConfig;
  let cachedRuntimeCode: string | undefined;
  const { sources, generator: generatorOptions } = options;

  const writeDeclarations = async (entries: AssetEntry[]) => {
    const dts = generateDeclarationModule(entries, generatorOptions);
    const fullPath = path.resolve(config.root, DECLARATION_FILE);
    await fs.mkdir(path.dirname(fullPath), { recursive: true });
    await fs.writeFile(fullPath, dts, "utf-8");
  };

  const regenerate = async () => {
    const entries = await scanAssets(sources);
    const runtimeCode = generateVirtualModule(entries, generatorOptions);
    await writeDeclarations(entries);
    cachedRuntimeCode = runtimeCode;
    return runtimeCode;
  };

  return {
    name: "vite-plugin-typed-assets",
    enforce: "pre",

    configResolved(resolvedConfig) {
      config = resolvedConfig;
    },

    resolveId(id) {
      if (id === ASSET_IMPORT_PATH) return RESOLVED_ASSET_IMPORT_PATH;
    },

    async load(id) {
      if (id === RESOLVED_ASSET_IMPORT_PATH) {
        if (!cachedRuntimeCode) await regenerate();
        return cachedRuntimeCode ?? "";
      }
    },

    async configureServer(server) {
      await regenerate();
    },

    async buildStart() {
      await regenerate();
    },
  };
}
