import type { AssetEntry, GeneratorOptions } from "../types";

export function generateRuntimeModule(
  entries: AssetEntry[],
  options: GeneratorOptions = {},
): string {
  const perType = options.perType ?? true;

  if (!perType) {
    return generateSingleModule(entries);
  }
  return generatePerTypeModule(entries);
}

function generatePerTypeModule(entries: AssetEntry[]): string {
  const groups = new Map<string, AssetEntry[]>();
  for (const entry of entries) {
    const existing = groups.get(entry.type) || [];
    existing.push(entry);
    groups.set(entry.type, existing);
  }

  let code = `// Auto-generated by typed-assets. DO NOT EDIT.\n\n`;
  const typeFuncMap: Record<string, string> = {
    image: "imagePath",
    video: "videoPath",
    audio: "audioPath",
    font: "fontPath",
    raw: "rawPath",
    generic: "assetPath",
  };

  for (const [type, assets] of groups.entries()) {
    if (assets.length === 0) continue;
    const constName = `${type}Assets`;
    const funcName = typeFuncMap[type] || "assetPath";

    // Plain JS object (no `as const`)
    code += `export const ${constName} = {\n`;
    for (const asset of assets) {
      code += `  "${asset.key}": "${asset.url}",\n`;
    }
    code += `};\n\n`;
    // Simple function that returns the object property
    code += `export function ${funcName}(key) {\n`;
    code += `  return ${constName}[key];\n`;
    code += `}\n\n`;
  }

  return code.trim() + "\n";
}

function generateSingleModule(entries: AssetEntry[]): string {
  let code = `// Auto-generated by typed-assets. DO NOT EDIT.\n\n`;
  code += `export const assets = {\n`;
  for (const entry of entries) {
    code += `  "${entry.key}": "${entry.url}",\n`;
  }
  code += `};\n\n`;
  code += `export function assetPath(key) {\n`;
  code += `  return assets[key];\n`;
  code += `}\n`;
  return code.trim() + "\n";
}

export function generateDeclarations(
  entries: AssetEntry[],
  options: GeneratorOptions = {},
): string {
  // The .d.ts file only needs the types and function signatures, no values.
  const perType = options.perType ?? true;
  if (!perType) {
    return generateSingleDeclarations(entries);
  }
  return generatePerTypeDeclarations(entries);
}

function generatePerTypeDeclarations(entries: AssetEntry[]): string {
  const groups = new Map<string, AssetEntry[]>();
  for (const entry of entries) {
    const existing = groups.get(entry.type) || [];
    existing.push(entry);
    groups.set(entry.type, existing);
  }

  let code = `// Auto-generated by typed-assets. DO NOT EDIT.\n\n`;
  const typeFuncMap: Record<string, string> = {
    image: "imagePath",
    video: "videoPath",
    audio: "audioPath",
    font: "fontPath",
    raw: "rawPath",
    generic: "assetPath",
  };

  for (const [type, assets] of groups.entries()) {
    if (assets.length === 0) continue;
    const typeName = `${capitalize(type)}Key`;
    const funcName = typeFuncMap[type] || "assetPath";

    // Declare the const as readonly object
    code += `export declare const ${type}Assets: {\n`;
    for (const asset of assets) {
      code += `  readonly "${asset.key}": "${asset.url}";\n`;
    }
    code += `};\n\n`;
    code += `export type ${typeName} = keyof typeof ${type}Assets;\n\n`;
    code += `export declare function ${funcName}(key: ${typeName}): string;\n\n`;
  }
  return code.trim() + "\n";
}

function generateSingleDeclarations(entries: AssetEntry[]): string {
  let code = `// Auto-generated by typed-assets. DO NOT EDIT.\n\n`;
  code += `export declare const assets: {\n`;
  for (const entry of entries) {
    code += `  readonly "${entry.key}": "${entry.url}";\n`;
  }
  code += `};\n\n`;
  code += `export type AssetKey = keyof typeof assets;\n\n`;
  code += `export declare function assetPath(key: AssetKey): string;\n`;
  return code.trim() + "\n";
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
