// Auto-generated by typed-assets. DO NOT EDIT.

declare module '@typest/vite' {
  export const imageAssets: {
    readonly "icons.svg": "/icons.svg";
    readonly "vite.svg": "/vite.svg";
    readonly "react.svg": "/assets/react.svg";
    readonly "favicon.svg": "/images/favicon.svg";
  };
  export type ImageKey = keyof typeof imageAssets;
  export function imagePath(key: ImageKey): string;

}
