/**
 * Generated by Typest CLI v1.0.2
 * Framework: vite
 *
 * This file enables typed asset imports.
 * Learn more: https://thetypest.vercel.app/plugin/vite.html
 *
 * You can safely modify it as needed.
 */

import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { typedAssets } from "@typest/vite/plugin";

export default defineConfig({
  plugins: [react(), typedAssets({ sources: [{ dir: 'public' }] })],
});
