// Auto-generated by typed-assets. DO NOT EDIT.

declare module "@typest/next" {
  export const imageAssets: {
    readonly "file.svg": "/file.svg";
    readonly "globe.svg": "/globe.svg";
    readonly "next.svg": "/next.svg";
    readonly "vercel.svg": "/vercel.svg";
    readonly "window.svg": "/window.svg";
  };
  export type ImageKey = keyof typeof imageAssets;
  export function imagePath(key: ImageKey): string;
}
